site_name: Crystmatch Documentation
site_author: Fang-Cheng Wang
repo_url: https://github.com/Fangcheng-Wang/crystmatch
repo_name: crystmatch

theme:
  name: 'material'

copyright: Copyright &copy; 2023–2024 Xin-Zheng Li Group. All rights reserved.

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - css/style-crystmatch.css

nav:
  - Tutorial: index.md
  - Command-line interface: cli.md
  - Python API: api.md
  - About: about.md

markdown_extensions:
  - admonition
  - tables
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - codehilite:
      guess_lang: false

plugins:
  - mkdocstrings
  - search